# Generated by Django 2.2.7 on 2019-11-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vat.Product'),
        ),
    ]
