# Generated by Django 2.2.7 on 2019-11-23 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0005_auto_20191123_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_list',
        ),
        migrations.AddField(
            model_name='order',
            name='product_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vat.Cart'),
            preserve_default=False,
        ),
    ]
