# Generated by Django 2.2.7 on 2019-11-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0007_auto_20191123_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
